---
- hosts: 127.0.0.1
  connection: local
  pre_tasks:
    - name: Check for preference file
      stat: path=preferences.fact
      register: preferences
      ignore_errors: yes
    - name: Create directory for ansible custom facts
      file: state=directory recurse=yes path=/etc/ansible/facts.d
      sudo: yes
      when: preferences.stat.exists
    - name: Install preferences custom fact
      copy: src=preferences.fact dest=/etc/ansible/facts.d
      sudo: yes
      when: preferences.stat.exists
    - name: Re-read facts after adding custom fact
      setup: filter=ansible_local
      when: preferences.stat.exists

    - name: Check if env is set
      shell: /bin/true
      register: env_set
      when: ansible_local is defined
            and ansible_local.preferences is defined
            and ansible_local.preferences.env is defined
            and ansible_local.preferences.env.name is defined

  roles:
    - common
    - { role: yum_packages, when: "ansible_pkg_mgr == 'yum'" }
    - { role: apt_packages, when: "ansible_pkg_mgr == 'apt'" }
    - { role: playhaven, when: "env_set is defined and env_set and ansible_local.preferences.env.name == 'playhaven'" }
